import { icons } from "lucide-react";

const legacyIconAliases: Record<string, keyof typeof icons> = {
  AlignCenter: "TextAlignCenter",
  AlignJustify: "TextAlignJustify",
  AlignLeft: "TextAlignStart",
  AlignRight: "TextAlignEnd",
  Angry: "FaceAngry",
  Annoyed: "FaceExpressionless",
  AreaChart: "ChartArea",
  ArrowDownRightSquare: "SquareArrowDownRight",
  ArrowLeftCircle: "CircleArrowLeft",
  ArrowLeftSquare: "SquareArrowLeft",
  ArrowRightCircle: "CircleArrowRight",
  ArrowRightSquare: "SquareArrowRight",
  ArrowUpCircle: "CircleArrowUp",
  ArrowUpLeftFromCircle: "CircleArrowOutUpLeft",
  ArrowUpLeftSquare: "SquareArrowUpLeft",
  ArrowUpSquare: "SquareArrowUp",
  Smile: "FaceSlightlySmiling",
};

export const resolveIconName = (name: string): keyof typeof icons => {
  const resolvedName = legacyIconAliases[name] ?? name;
  return resolvedName in icons
    ? (resolvedName as keyof typeof icons)
    : "CircleQuestionMark";
};

const requestedIcons = [
  "Accessibility",
  "Activity",
  "AirVent",
  "Airplay",
  "AlarmClockOff",
  "AlarmClock",
  "Album",
  "AlignCenterHorizontal",
  "AlignCenterVertical",
  "TextAlignCenter",
  "AlignEndHorizontal",
  "AlignEndVertical",
  "AlignHorizontalDistributeCenter",
  "AlignHorizontalDistributeEnd",
  "AlignHorizontalDistributeStart",
  "AlignHorizontalJustifyCenter",
  "AlignHorizontalJustifyEnd",
  "AlignHorizontalJustifyStart",
  "AlignHorizontalSpaceAround",
  "AlignHorizontalSpaceBetween",
  "TextAlignJustify",
  "TextAlignStart",
  "TextAlignEnd",
  "AlignStartHorizontal",
  "AlignStartVertical",
  "AlignVerticalDistributeCenter",
  "AlignVerticalDistributeEnd",
  "AlignVerticalDistributeStart",
  "AlignVerticalJustifyCenter",
  "AlignVerticalJustifyEnd",
  "AlignVerticalJustifyStart",
  "AlignVerticalSpaceAround",
  "AlignVerticalSpaceBetween",
  "Ampersand",
  "Ampersands",
  "Anchor",
  "FaceAngry",
  "FaceExpressionless",
  "Antenna",
  "Aperture",
  "AppWindow",
  "Apple",
  "ArchiveRestore",
  "ArchiveX",
  "Archive",
  "ChartArea",
  "Armchair",
  "ArrowBigDownDash",
  "ArrowBigDown",
  "ArrowBigLeftDash",
  "ArrowBigLeft",
  "ArrowBigRightDash",
  "ArrowBigRight",
  "ArrowBigUpDash",
  "ArrowBigUp",
  "ArrowDown01",
  "ArrowDown10",
  "ArrowDownAZ",
  "ArrowDownFromLine",
  "ArrowDownLeft",
  "ArrowDownNarrowWide",
  "SquareArrowDownRight",
  "ArrowDownRight",
  "ArrowDownToDot",
  "ArrowDownToLine",
  "ArrowDownUp",
  "ArrowDownWideNarrow",
  "ArrowDownZA",
  "ArrowDown",
  "CircleArrowLeft",
  "ArrowLeftFromLine",
  "ArrowLeftRight",
  "SquareArrowLeft",
  "ArrowLeftToLine",
  "ArrowLeft",
  "CircleArrowRight",
  "ArrowRightFromLine",
  "ArrowRightLeft",
  "SquareArrowRight",
  "ArrowRightToLine",
  "ArrowRight",
  "ArrowUp01",
  "ArrowUp10",
  "ArrowUpAZ",
  "CircleArrowUp",
  "ArrowUpDown",
  "ArrowUpFromDot",
  "ArrowUpFromLine",
  "CircleArrowOutUpLeft",
  "SquareArrowUpLeft",
  "ArrowUpLeft",
  "ArrowUpNarrowWide",
  "ArrowUpRight",
  "SquareArrowUp",
  "ArrowUpToLine",
  "ArrowUpWideNarrow",
  "ArrowUpZA",
  "ArrowUp",
  "ArrowsUpFromLine",
  "Asterisk",
  "AtSign",
  "Atom",
  "Award",
  "Axe",
  "Axis3d",
] as const;

// Lucide occasionally renames icons. Never render a picker tile for an export
// that is not present in the installed version of the library.
export const iconList: string[] = requestedIcons.filter(
  (name) => name in icons,
);
